//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backup.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int MainWindow_ListView_Column_1_Width {
            get {
                return ((int)(this["MainWindow_ListView_Column_1_Width"]));
            }
            set {
                this["MainWindow_ListView_Column_1_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int MainWindow_ListView_Column_2_Width {
            get {
                return ((int)(this["MainWindow_ListView_Column_2_Width"]));
            }
            set {
                this["MainWindow_ListView_Column_2_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int MainWindow_ListView_Column_3_Width {
            get {
                return ((int)(this["MainWindow_ListView_Column_3_Width"]));
            }
            set {
                this["MainWindow_ListView_Column_3_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int MainWindow_ListView_Column_4_Width {
            get {
                return ((int)(this["MainWindow_ListView_Column_4_Width"]));
            }
            set {
                this["MainWindow_ListView_Column_4_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int MainWindow_ListView_Column_5_Width {
            get {
                return ((int)(this["MainWindow_ListView_Column_5_Width"]));
            }
            set {
                this["MainWindow_ListView_Column_5_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int BackupHistoryDialog_ListView_Column_1_Width {
            get {
                return ((int)(this["BackupHistoryDialog_ListView_Column_1_Width"]));
            }
            set {
                this["BackupHistoryDialog_ListView_Column_1_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int BackupHistoryDialog_ListView_Column_2_Width {
            get {
                return ((int)(this["BackupHistoryDialog_ListView_Column_2_Width"]));
            }
            set {
                this["BackupHistoryDialog_ListView_Column_2_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int BackupHistoryDialog_ListView_Column_3_Width {
            get {
                return ((int)(this["BackupHistoryDialog_ListView_Column_3_Width"]));
            }
            set {
                this["BackupHistoryDialog_ListView_Column_3_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int BackupHistoryDialog_ListView_Column_4_Width {
            get {
                return ((int)(this["BackupHistoryDialog_ListView_Column_4_Width"]));
            }
            set {
                this["BackupHistoryDialog_ListView_Column_4_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int BackupHistoryDialog_ListView_Column_5_Width {
            get {
                return ((int)(this["BackupHistoryDialog_ListView_Column_5_Width"]));
            }
            set {
                this["BackupHistoryDialog_ListView_Column_5_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SearchUpdatesMode {
            get {
                return ((int)(this["SearchUpdatesMode"]));
            }
            set {
                this["SearchUpdatesMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int ErrorLogDialog_ListView_Column_1_Width {
            get {
                return ((int)(this["ErrorLogDialog_ListView_Column_1_Width"]));
            }
            set {
                this["ErrorLogDialog_ListView_Column_1_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int ErrorLogDialog_ListView_Column_2_Width {
            get {
                return ((int)(this["ErrorLogDialog_ListView_Column_2_Width"]));
            }
            set {
                this["ErrorLogDialog_ListView_Column_2_Width"] = value;
            }
        }
    }
}
